name: ESLint

on:
  push:
    branches:
      - main
      - development
  schedule:
    - cron: '42 16 * * 3'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: ESLint
        run: yarn lint

      - name: Build
        run: yarn build:all

      - name: Build Android
        run: yarn android:bundle

      - name: Test
        run: yarn test
